--- #YAML:1.0
name:                Tk-Text-Viewer
version:             0.94
abstract:            Read only Tk Text Widget with search capability
license:             ~
author:              
    - Oded S. Resnik <razinf at cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Tk:                            0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
